version: '3'
services:
  web:
    image: nginx
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
  app:
    depends_on:
      - db
    build: ./docker/app
    volumes:
      - .:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_exam
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=docker_user
      - PMA_PASSWORD=docker_pass
    ports:
      - "3000:80"
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
